connections:
  postgresql:
    adapter: postgresql
    database: apartment_postgresql_test
    username: root
    password: 

  mysql:
    adapter: mysql
    database: apartment_mysql_test
    username: root
    password: 
